# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 3179c16
_src_path: gh:schwallergroup/copier-liac-minimal
author_email: ralphgebran41@gmail.com
author_name: Ralph GEBRAN
github_org: ralphgebran
package_name: greenchempanion
project_name: greenchempanion
short_description: Your interactive companion for Green Chemistry
